import{Assessment,Movement,Plan,Workout,WorkoutExercise}from'../types';import{exercises}from'../data/exercises';
const patterns:Movement[]=['Squat','Hinge','Horizontal Push','Horizontal Pull','Vertical Push','Vertical Pull','Core'];
function available(e:any,a:Assessment){if(e.equipment.includes('No Equipment'))return true;return e.equipment.some((x:string)=>a.equipment.includes(x))}
function safe(e:any,a:Assessment){return!e.avoidTags.some((t:string)=>a.limitations.includes(t))&&!a.avoid.toLowerCase().split(/[,;]+/).some(x=>x.trim().length>2&&e.name.toLowerCase().includes(x.trim()))}
function pick(pattern:Movement,a:Assessment,used:Set<string>){let pool=exercises.filter(e=>e.movement===pattern&&e.difficulty.includes(a.level)&&e.goals.includes(a.goal as any)&&available(e,a)&&safe(e,a)&&!used.has(e.name));if(!pool.length)pool=exercises.filter(e=>e.movement===pattern&&e.difficulty.includes(a.level)&&available(e,a)&&safe(e,a)&&!used.has(e.name));const preferred=pool.find(e=>(a.preferences.includes('Bodyweight Training')&&e.equipment.includes('No Equipment'))||(a.preferences.includes('Weight Training')&&!e.equipment.includes('No Equipment')));return preferred||pool[0]}
function split(a:Assessment){if(a.days===1)return['Full Body'];if(a.days===2)return['Full Body A','Full Body B'];if(a.days===3)return a.level==='Beginner'?['Full Body A','Full Body B','Full Body C']:['Upper Body','Lower Body','Full Body'];if(a.days===4)return['Upper Body A','Lower Body A','Upper Body B','Lower Body B'];if(a.days===5)return a.goal==='Improve Endurance'?['Full Body','Cardio & Core','Upper Body','Lower Body','Conditioning']:['Upper Body','Lower Body','Full Body','Upper Focus','Lower Focus'];return['Upper Body','Lower Body','Cardio & Core','Upper Body','Lower Body','Functional / Conditioning',...(a.days===7?['Recovery / Mobility']:[])].slice(0,a.days)}
function patternSet(title:string){if(title.includes('Upper'))return['Horizontal Push','Horizontal Pull','Vertical Push','Vertical Pull','Core'] as Movement[];if(title.includes('Lower'))return['Squat','Hinge','Core'] as Movement[];if(title.includes('Cardio')||title.includes('Conditioning')||title.includes('Recovery'))return['Core'] as Movement[];return patterns}
function maxExercises(a:Assessment){return{'15–20 minutes':3,'30 minutes':4,'45 minutes':5,'60 minutes':6,'75 minutes':7,'90+ minutes':7}[a.duration]||5}
function cardio(a:Assessment,title:string){const likes=a.preferences;let activity=likes.includes('Cycling')?'Cycling':likes.includes('Running')?'Jogging / running':likes.includes('Walking')?'Brisk walking':a.equipment.includes('Exercise Bike')?'Exercise bike':a.equipment.includes('Treadmill')?'Brisk treadmill walking':'Brisk walking';let mins=a.duration==='15–20 minutes'?10:a.duration==='30 minutes'?15:20;if(a.goal==='Improve Endurance')mins+=10;if(title.includes('Cardio')||title.includes('Conditioning'))mins=Math.max(20,mins);return`${activity} — ${mins} minutes — conversational to moderate pace`}
export function generatePlan(a:Assessment):Plan{const titles=split(a),workouts:Workout[]=[];titles.forEach((title,i)=>{const used=new Set<string>(),chosen:WorkoutExercise[]=[];for(const p of patternSet(title)){if(chosen.length>=maxExercises(a))break;const e=pick(p,a,used);if(e){used.add(e.name);chosen.push({...e,sets:a.level==='Beginner'?2:(a.goal==='Build Muscle'?3:3),rest:a.goal==='Gain Strength'?'120 sec':p==='Core'?'45–60 sec':'75–90 sec',rpe:a.level==='Beginner'?'RPE 6–7':a.level==='Intermediate'?'RPE 7–8':'RPE 7–8'})}}workouts.push({day:a.preferredDays[i]||`Day ${i+1}`,title,warmup:'5–10 min of easy movement, dynamic preparation and light practice sets for the first exercises.',exercises:chosen,cardio:(a.goal==='Lose Body Fat'||a.goal==='Improve Endurance'||title.includes('Cardio')||title.includes('Conditioning'))?cardio(a,title):undefined,cooldown:'Optional: 3–5 minutes of easy movement and comfortable mobility or stretching.'})});
const schedule=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map(day=>{const w=workouts.find(x=>x.day===day);return{day,activity:w?w.title:(a.preferences.includes('Walking')?'Recovery / optional easy walking':'Rest / recovery')}});
const block=a.level==='Beginner'?'manageable volume, fundamental movement patterns and gradual skill development':a.level==='Intermediate'?'balanced weekly volume with progressive overload and recovery':'goal-specific volume, controlled higher effort and deliberate recovery';
const strategy=`Your ${a.days}-day plan uses ${titles.join(', ')} because you selected ${a.goal.toLowerCase()} as your primary goal and identified as ${a.level.toLowerCase()}. Sessions are designed for ${a.duration}, use only compatible selected equipment, and emphasize ${block}.`;
let progression=[] as Plan['progression'];if(a.weeks===4)progression=[{phase:'Foundation',weeks:'Weeks 1–2',description:'Establish technique, suitable loads and repeatable effort.'},{phase:'Build',weeks:'Weeks 3–4',description:'Add repetitions or small resistance increases when form and target RPE allow.'}];else if(a.weeks===6)progression=[{phase:'Foundation',weeks:'Weeks 1–2',description:'Learn the plan and establish baseline loads.'},{phase:'Build',weeks:'Weeks 3–4',description:'Progress repetitions within the prescribed ranges.'},{phase:'Consolidate',weeks:'Weeks 5–6',description:'Use small load or duration increases while protecting recovery.'}];else progression=[{phase:'Foundation',weeks:'Weeks 1–2',description:'Learn exercises, establish technique and choose appropriate resistance.'},{phase:'Build',weeks:'Weeks 3–4',description:'Gradually add quality repetitions or small resistance increases.'},{phase:'Progress',weeks:`Weeks 5–${Math.max(6,a.weeks-2)}`,description:'Continue progressive overload while maintaining technique and recovery.'},{phase:'Review',weeks:`Weeks ${a.weeks-1}–${a.weeks}`,description:'Consolidate progress, avoid forced increases, and assess the next training phase.'}];
return{strategy,schedule,workouts,progression,safety:[...(a.hasLimitations?['Your reported limitations were used to avoid flagged exercises where possible. Exercise should remain comfortable; seek qualified assessment for persistent or significant symptoms.']:[]),...(a.redFlags.length?['You reported a potentially significant health or physical consideration. Obtain appropriate medical or qualified professional guidance before beginning or modifying exercise.']:[]),'Stop exercising and seek appropriate medical attention if you experience chest pain, fainting, severe shortness of breath, sudden severe pain, or other concerning symptoms.','This plan provides general fitness guidance and is not medical advice, diagnosis, physiotherapy, or individualized treatment.']}}
